abstract: Markup As YAML
author: Kang-min Liu  C<< <gugod@gugod.org> >>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Markaya
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Entities: 0
  YAML::LibYAML: 0.16
  perl: 5.8.3
version: 0.0.2
